issue-2-view-agent-details
jeff-cruz/valorant-comp-builder pull request #7
Opened 2022-04-20 18:27 UTC by jeff-cruz

![Kapture 2022-04-20 at 11 24 40](https://user-images.githubusercontent.com/99565410/164297924-14655586-d338-44ca-a5f3-dee04862a88c.gif)

2022-04-20 18:31 UTC, codingcodymiller requested changes

2022-04-20 18:31 UTC, codingcodymiller commented on js/main.js
> +          $abilityFourText.textContent = xhr.response.data[i].abilities[3].description;
Why not do this with a loop over the `abilities` array?

2022-04-20 18:31 UTC, codingcodymiller commented on js/main.js
> +          $abilityFourContainer.appendChild($abilityFourText);
Why not do this with a loop?

2022-04-20 19:34 UTC, codingcodymiller requested changes

2022-04-20 19:34 UTC, codingcodymiller commented on js/main.js
> +            }
This is still the same problem. You should be able to make the elements, configure the elements, and append the elements inside of this loop. There should be no conditional necessary.

2022-04-20 22:20 UTC, jeff-cruz commented
![Kapture 2022-04-20 at 15 18 24](https://user-images.githubusercontent.com/99565410/164334460-a3e382dd-aaed-47d9-84ab-df910c6c404d.gif)

2022-04-21 00:14 UTC, codingcodymiller approved these changes

2022-04-21 00:16 UTC, merged